apiVersion: v1
name: sso-keycloak
version: 1.17.2
appVersion: 26.4.11-build.1
description: Open Source Identity and Access Management For Modern Applications and Services
dependencies:
  - name: patroni
    version: 1.6.1
    repository: https://bcgov.github.io/sso-helm-charts
    tags:
      - patroni-enabled
